### ISSUE TITLE
v0.8.0 - A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by aalemayhu** [kyleparisi/Fluxion#3]
Seeing the below error when launching the DMG install

![Screenshot 2019-06-08 at 1 53 14 PM](https://user-images.githubusercontent.com/925044/59146957-0d9e9400-89f5-11e9-885e-6b0dfbd5d817.png)

Text below for copy paste
```
Uncaught Exception:
Error: Cannot find module 'vue-devtools'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._resolveFilename (/Applications/Fluxion.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at App.createWindow (/Applications/Fluxion.app/Contents/Resources/app.asar/electron-starter.js:18:3)
    at App.emit (events.js:187:15)
```

**Comment by kyleparisi** [comment]
hm I don't know how I missed this issue sorry.  I've commented out that part a little while ago.  Hopefully is not still happening.
